linters:
  enable:
    - gofmt
    - gocyclo
    - revive
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - exportloopref
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
