setrequest:
  prefix:
    elem:
    - name: e2node
  delete: []
  replace: []
  update:
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001420
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
        key: {}
      - name: RadioMeasReportPerCell
      target: 315010-0001420
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001421
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001421
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001422
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001422
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001423
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001423
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001424
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001424
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001425
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001425
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001426
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001426
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001427
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001427
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001428
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001428
    val:
      uintvalue:
        uintval: 21
  extension: []
