mapcentre:
  lat: 52.52
  lng: 13.405
towerslayout:
- towerid: Tower-1
  plmnid: "315010"
  latitude: 52.48536
  longitude: 13.405
  sectors:
  - ecid: "0001420"
    grpcport: 5152
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001421"
    grpcport: 5153
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001422"
    grpcport: 5154
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-2
  plmnid: "315010"
  latitude: 52.50268
  longitude: 13.454303
  sectors:
  - ecid: "0001423"
    grpcport: 5155
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001424"
    grpcport: 5156
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001425"
    grpcport: 5157
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-3
  plmnid: "315010"
  latitude: 52.50268
  longitude: 13.355697
  sectors:
  - ecid: "0001426"
    grpcport: 5158
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001427"
    grpcport: 5159
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001428"
    grpcport: 5160
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-4
  plmnid: "315010"
  latitude: 52.52
  longitude: 13.405
  sectors:
  - ecid: "0001429"
    grpcport: 5161
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: 000142a
    grpcport: 5162
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: 000142b
    grpcport: 5163
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-5
  plmnid: "315010"
  latitude: 52.53732
  longitude: 13.454303
  sectors:
  - ecid: 000142c
    grpcport: 5164
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: 000142d
    grpcport: 5165
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: 000142e
    grpcport: 5166
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-6
  plmnid: "315010"
  latitude: 52.53732
  longitude: 13.355697
  sectors:
  - ecid: 000142f
    grpcport: 5167
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001430"
    grpcport: 5168
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001431"
    grpcport: 5169
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
- towerid: Tower-7
  plmnid: "315010"
  latitude: 52.55464
  longitude: 13.405
  sectors:
  - ecid: "0001432"
    grpcport: 5170
    azimuth: 0
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001433"
    grpcport: 5171
    azimuth: 120
    arc: 120
    maxues: 5
    initpowerdb: 10
  - ecid: "0001434"
    grpcport: 5172
    azimuth: 240
    arc: 120
    maxues: 5
    initpowerdb: 10
