setrequest:
  prefix:
    elem:
    - name: e2node
    target: ""
  delete: []
  replace: []
  update:
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001420
    val:
      stringvalue: null
      intvalue: null
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001420
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001421
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001421
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001422
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001422
    val:
      uintvalue:
        uintval: 21
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerUe
      target: 315010-0001423
    val:
      uintvalue:
        uintval: 20
  - path:
      elem:
      - name: intervals
      - name: RadioMeasReportPerCell
      target: 315010-0001423
    val:
      uintvalue:
        uintval: 21
  extension: []
